server:
  mode: "debug"         # possible value: debug, test and release
  addr: ":8080"         # listen address and port
  logDuration: 3        # log buffering duration in second
  shutdownTimeout: 5    # shutdown timeout duration in second
  baseUrl: "http://localhost:8080"

database:
  dbType: "mysql"       # possible value: mssql, mysql, postgres and sqlite 
  connectionUri: "root:root@tcp(localhost:3306)/fmanagement?tls=skip-verify&autocommit=true&parseTime=true"